services:
  wordpress:
    container_name: wordpress
    image: wordpress:latest
    ports:
      - 8080:80
    restart: always
    environment:
      - WORDPRESS_DB_HOST=wordpress-db
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
      - WORDPRESS_DB_NAME=wordpress
    networks:
      - default-network
  wordpress-db:
    container_name: wordpress-db
    image: mysql:8.0
    volumes:
      - wordpressdb-data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress
      - MYSQL_RANDOM_ROOT_PASSWORD=1
    expose:
      - 3306
      - 33060
    networks:
      - default-network

volumes:
  wordpressdb-data:
    name: wordpressdb-data
