services:
  fossbilling-micro:
    container_name: fossbilling-micro
    build:
      context: ./micro
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8001:8001
    networks:
      - default-network
    depends_on:
      - rabbitmq
  fossbilling:
    container_name: fossbilling
    image: fossbilling/fossbilling
    restart: always
    ports:
      - 8000:80
    volumes:
      - fossbilling-data:/var/www/html
    networks:
      - default-network
  fossbilling-db:
    container_name: fossbilling-db
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: fossbilling
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_RANDOM_ROOT_PASSWORD: "1"
    volumes:
      - fossbillingdb-data:/var/lib/mysql
    networks:
      - default-network

volumes:
  fossbilling-data:
    name: fossbilling-data
  fossbillingdb-data:
    name: fossbillingdb-data
