services:
  fossbilling:
    image: fossbilling/fossbilling
    restart: always
    ports:
      - 8000:80
    volumes:
      - fossbilling:/var/www/html
  fossbilling-db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: fossbilling
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_RANDOM_ROOT_PASSWORD: "1"
    volumes:
      - fossbilling-data:/var/lib/mysql

volumes:
  fossbilling:
  fossbilling-data:
